コンテキストを維持して対話できる関数の追加
halca-crowd/chat-tkb pull request #1
Opened 2023-10-31 18:25 UTC by 23akei

throwChatStreamRequests()を実装。
引数と戻り値に[]openai.ChatCompletionMessage型で既存メッセージのやり取りができるようにした。

2023-10-31 18:50 UTC, 23akei commented
ChatMessageとRoleを定義してそれらでやり取りするように。

2023-11-01 14:07 UTC, notchman8600 commented
勝手にnetlifyのCIが回ってる😇

2023-11-01 14:09 UTC, notchman8600 commented on backend/src/openai.go
> +func throwChatStreamRequests(client *openai.Client, model string, prompt string, max_tokens int, history []ChatMessage) ([]ChatMessage, error) {
プロンプトの登録のメイン同線はhandler.goのL40-からの処理になっています。`requestObject.Message`にプロンプトがある想定なので、こちらも貯めるようにしていただけると助かります。

2023-11-01 15:28 UTC, notchman8600 requested changes
決め打ちで良いので`gpt-3.5-16k`的なモデルを使うようにしていただければ...🙏

2023-11-01 15:28 UTC, notchman8600 commented on backend/src/handler.go
> +			return errorResponseFactory("faile to fetch chat history", 503, "failed to fetch chat history")
ここが取れないときはプロンプトだけで後続処理を走らせたいですね。だからreturnはしなくて良いかなと思います。

2023-11-01 15:28 UTC, notchman8600 commented on backend/src/openai.go
> +	}
この処理があるのでhistoryが取れないときは処理を続行させれば良いかなと思います。

2023-11-01 16:53 UTC, notchman8600 approved these changes
ヨシッ！

2023-11-01 16:56 UTC, merged